<table class="headbox">
	<tr>
		<td colspan="4" id="big-logo">
			<a class="vis-desktop" href="//rule34.paheal.net/post/list"><img alt="logo" src="//rule34.paheal.net/themes/rule34v2/rule34_logo_top.png" style="height: 104px;"/></a>
		</td>
	</tr>

	<tr>
		<form action='/post/list' method='GET' id="barbot">
			<td id="nav-toggle">
				<a style="font-size: 2em;" onclick="toggleNav();">&nbsp;Sidebar&nbsp;</a>
			</td>
			<td id="mini-logo">
				<a class="vis-mobile" href="//rule34.paheal.net/post/list"><img alt="logo" src="//rule34.paheal.net/themes/rule34v2/rule34_logo_top.png" style="height: 34px;"/></a>
			</td>
			<td>
				<input name='search' size="45" type='text' placeholder='Search' autocomplete='off' class='autocomplete_tags' value="<?=$query;?>"/>
			</td>
			<td width="100">
				<input type='submit' value='Find' id="submit" style="border: 1px solid #888; height: 34px; border-radius: 2px; background: #EEE;"/>
			</td>
		</form>
	</tr>

	<tr>
		<td colspan="4">
<div id="menuh-container">
<div id="menuh">

	<ul>
		<li><a href="//rule34.paheal.net/post/list" class="top_parent">Main &#9660;</a>
		<ul>
			<li><a href="//rule34.paheal.net/post/list" class="sub_option">Home page</a></li>
			<li><a href="//rule34.paheal.net/comment/list" class="sub_option">Comments</a></li>
			<li><a href="//rule34.paheal.net/tags" class="sub_option">Tags</a></li>
			<li><a href="//rule34.paheal.net/upload" class="sub_option">Upload</a></li>
		</ul>
		</li>
	</ul>
    
    <!--<ul class="header-sites">	
		<li><a href="#" class="top_parent">Sites</a>
		<ul>
			<li><a href="//rule34.paheal.net/" class="sub_option">Rule #34</a></li>
			<li><a href="http://rule63.paheal.net/" class="sub_option">Rule #63</a></li>
			<li><a href="http://cosplay.paheal.net/" class="sub_option">Cosplay</a></li>
			<li><a href="//rule34c.paheal.net/" class="sub_option">Rule #34c</a></li>
		</ul>
		</li>
	</ul>-->
    
	<ul>
		<li><a href="#" class="top_parent">Community &#9660;</a>
		<ul>
			<!--<li><a href="http://forum.paheal.net" class="sub_option">Forum</a></li>-->
			<li><a href="//rule34.paheal.net/wiki/friends" class="parent">Friends of paheal</a>
			<li><a href="//rule34.paheal.net/wiki/DNP" class="parent">DNP List</a>
			<li><a href="#" class="parent">Chat</a>
			<ul>
				<li><a href="irc://irc.rizon.net/rule34" class="sub_option">irc.rizon.net/rule34</a></li>
				<li><a href="http://widget.mibbit.com/?server=irc.rizon.net&nick=Anon%3F%3F%3F&channel=%23rule34" target="new" class="sub_option">Web Chat</a></li>
			</ul>
			</li>
		</ul>
		</li>
	</ul>

	<ul>
		<li><a href="//rule34.paheal.net/post/list" class="top_parent">Help &#9660;</a>
		<ul>
			<li><a href="//rule34.paheal.net/wiki/rules" class="sub_option">Site rules</a></li>
            <li><a href="//rule34.paheal.net/wiki/faq" class="sub_option">F.A.Q.</a></li>
			<li><a href="//rule34.paheal.net/wiki/tagging" class="sub_option">Tagging Guide</a></li>
			<li><a href="//rule34.paheal.net/wiki/staff" class="sub_option">Staff</a></li>
			<li><a href="#" class="parent">Contact</a>
			<ul>
				<li><a href="mailto:staff@paheal.net" class="sub_option">Staff</a></li>
				<li><a href="mailto:webmaster@shishnet.org" class="sub_option">Programmer</a></li>
			</ul>
			</li>
		</ul>
		</li>
	</ul>
	
	<ul>
		<li><a class="menu top_parent" href="//rule34.paheal.net/wiki/Notes">ANNOUNCEMENTS</a></li>
	</ul>

	<ul>
		<li><a class="menu top_parent" href="https://s.zlink2.com/splash.php?idzone=3832265&return_url=" target="_blank" style="color: red;">Cunt Empire!</a></li>
	</ul>
	
</div>
</div>

		</td>
	</tr>
</table>
