version: 2
updates:
- package-ecosystem: github-actions
  assignees:
    - shish
  directory: /
  schedule:
    interval: monthly
- package-ecosystem: composer
  assignees:
    - shish
  directory: /
  schedule:
    interval: monthly
  groups:
    minor-bumps:
      applies-to: version-updates
      patterns:
      - '*'
      update-types:
      - minor
      - patch
- package-ecosystem: docker
  assignees:
    - shish
  directory: /
  schedule:
    interval: monthly
